import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

# Use a service account.
cred = credentials.Certificate("lps3.json")
app = firebase_admin.initialize_app(cred)
db = firestore.client()

cadetNo=[3128,3129,3130,3131,3132,3133,3134,3135,3136,3137,3138,3140,3141,3142,3143,3144,3145,3146,3147,3148,3149,3150,3151,3152,3153,3154,3155,3156,3157,3158,3159,3160,3161,3162,3163,3164,3165,3166,3167,3168,3169,3170,3172,3173,3174,3175,3176,3177,3178,3179,3180,3181,3182,3183,3184,3185,3186,3187,3188,3189,3190,3191,3192,3193,3194,3195,3196,3197,3198,3199,3200,3201,3202,3203,3204,3205,3206,3207,3208,3209,3210,3211,3212,3213,3214,3215,3216,3217,3218,3219,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229,3230,3231]
name=["Nafi","Marjuk","Dahian","Imran","Fatin","Irbazz","Sanjid","Soumyadip","Nihal","Suslan","Fahad","Tahlil","Jareed","Salehin","Nirob","Azim","Nishad","Towfiq","Tahmid","Omi","Tanvir","Zaiaan","Arif","Mahfuz","Nabil","Ariyan","Shahir","Mahmud","Tawsif","Naimur","Sakib","Rakibul","Islam","Taseen","Ashfaq","Muktadir","Abid","Zarif","Rahim","Mahdi","Fuad","Rafsan","Mushfiq","Siam","Jahin","Redwan","Yean","Asif","Sadman","Galib","Mahin","Hamim","Prottoy","Noman","Nur","Jawad","Arabi","Ridwan","Tanvir","Tajwar","Rahat","Rafi","Nahfiz","Mostofa","Nasif","Mursalin","Sufian","Jonayed","Nirjhor","Sourov","Saud","Mahmud","Bilawal","Iqbal","Muhit","Ahnaf","Junaid","Jahin","Nabil","Abdulla","Rayan","Soham","Arif","Nubaid","Rakib","Abrar","Shahin","Tawsif","Rahid","Parvez","Mahir","Muktadir","Mahin","Nihan","Nishan","Nafees","Mortuza","Tawhid","Shahriar","Ehsan","Hossain","Arafat"]
classs=["IX","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VIII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII","VII"]
form=["B","A","B","A","B","A","B","A","B","A","B","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A","B","A"]
house=["Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Khalid","Tariq","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid","Qasim","Tariq","Khalid"]
at=["present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present","present"]

for i in range(len(cadetNo)):
      doc = db.collection("Cadets").document(f"{cadetNo[i]}")
      doc.set({"name": f"{name[i]}", "class": f"{classs[i]}", "form":f"{form[i]}", "house":f"{house[i]}", "at":f"{at[i]}"})


